Enhanced satori client
heroiclabs/nakama-swift pull request #46
Opened 2024-03-14 18:43 UTC by fsufyan

Several fixes and api enhancements, also added more tests.

2024-03-15 23:16 UTC, lugehorsam commented on Sources/Satori/Models/Experiment.swift
> +    let experiments: [ApiExperiment]
Should this be `let experiments: [Experiment]`?

2024-03-15 23:17 UTC, lugehorsam commented on Sources/Satori/Models/Flag.swift
> +    let flags: [ApiFlag]
Should this be `[Flag]`

2024-03-15 23:17 UTC, lugehorsam requested changes
just two minor comments

2024-03-16 09:47 UTC, fsufyan commented
> just two minor comments

Fixed, the type in Experiment and Flag lists is left without optional to avoid optional chaining ?.
Users could check for empty list instead of nil.

2024-03-18 17:44 UTC, lugehorsam approved these changes

2024-03-18 17:44 UTC, merged